on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip the extension
        run: |
          7z a -mx=9 -mtc=off extension.zip img js manifest.json
          mv extension.zip extension.xpi
      - name: Upload extension
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension.xpi
