on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip the extension
        run: zip extension.zip * -x .git* *.png *.jpg img README.md
      - name: Upload extension
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension.zip
